name: Bug Report
description: Something broken / not working as expected
title: '[bug] '
labels: ['bug']
body:
  - type: input
    id: page
    attributes:
      label: Page
      description: What page did this happen on?
      placeholder: ex. https://beta.discordlist.gg/bot/:id
    validations:
      required: false
  - type: textarea
    id: description
    attributes:
      label: Description
      description: "Please upload images if possible."
      placeholder: 'Describe the bug here'
    validations:
      required: true
  # - type: dropdown
  #   id: version
  #   attributes:
  #     label: Version
  #     description: What version of our software are you running?
  #     options:
  #       - 1.0.2 (Default)
  #       - 1.0.3 (Edge)
  # validations:
  #   required: true
  # - type: dropdown
  #   id: browsers
  #   attributes:
  #     label: What browsers are you seeing the problem on?
  #     multiple: true
  #     options:
  #       - Firefox
  #       - Chrome
  #       - Safari
  #       - Microsoft Edge
  #  - type: checkboxes
  #   id: terms
  #   attributes:
  #     label: Code of Conduct
  #     description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com)
  #     options:
  #       - label: I agree to follow this project's Code of Conduct
  #         required: true
  # - type: textarea
  #   id: logs
  #   attributes:
  #     label: Website data
  #     description: Please paste in the website data. This is found in the bug icon bottom right on the website.
  #     render: JSON
  - type: checkboxes
    id: terms
    attributes:
      label: Notify on issue updates
      description: Do you want us to ping you on Discord if we require more information from you?
      options:
        - label: Yes
  - type: input
    id: page
    attributes:
      label: Discord username
      description: If you checked the box above, what's your username?
      placeholder: ex. audn#1580
