name: Design/UI
description: Design that can be confused with a bug
title: '[ui] '
labels: ['ui']
assignees:
  - audn
body:
  - type: input
    id: page
    attributes:
      label: Page
      placeholder: ex. https://beta.discordlist.gg/bot/:id
    validations:
      required: false
  - type: textarea
    id: description
    attributes:
      label: Description
      description: 'Please upload images if possible.'
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      description: "Please test on multiple browsers if you're not using Chrome"
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
  - type: checkboxes
    id: terms
    attributes:
      label: Notify on issue updates
      description: Do you want us to ping you on Discord if we require more information from you?
      options:
        - label: "Yes"
  - type: input
    id: discordname
    attributes:
      label: Discord username
      description: If you checked the box above, what's your username?
      placeholder: ex. audn#1580
